"""add created_at indexes and add cascade delete

Revision ID: d5e138832a75
Revises: a96292c5d628
Create Date: 2026-01-05 11:59:12.455073+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5e138832a75'
down_revision: Union[str, None] = 'a96292c5d628'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.drop_constraint(op.f('messages_thread_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'threads', ['thread_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_run_steps_created_at'), 'run_steps', ['created_at'], unique=False)
    op.drop_constraint(op.f('run_steps_thread_id_fkey'), 'run_steps', type_='foreignkey')
    op.drop_constraint(op.f('run_steps_run_id_fkey'), 'run_steps', type_='foreignkey')
    op.create_foreign_key(None, 'run_steps', 'runs', ['run_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'run_steps', 'threads', ['thread_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_runs_created_at'), 'runs', ['created_at'], unique=False)
    op.drop_constraint(op.f('runs_thread_id_fkey'), 'runs', type_='foreignkey')
    op.create_foreign_key(None, 'runs', 'threads', ['thread_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_threads_created_at'), 'threads', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threads_created_at'), table_name='threads')
    op.drop_constraint(None, 'runs', type_='foreignkey')
    op.create_foreign_key(op.f('runs_thread_id_fkey'), 'runs', 'threads', ['thread_id'], ['id'])
    op.drop_index(op.f('ix_runs_created_at'), table_name='runs')
    op.drop_constraint(None, 'run_steps', type_='foreignkey')
    op.drop_constraint(None, 'run_steps', type_='foreignkey')
    op.create_foreign_key(op.f('run_steps_run_id_fkey'), 'run_steps', 'runs', ['run_id'], ['id'])
    op.create_foreign_key(op.f('run_steps_thread_id_fkey'), 'run_steps', 'threads', ['thread_id'], ['id'])
    op.drop_index(op.f('ix_run_steps_created_at'), table_name='run_steps')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_thread_id_fkey'), 'messages', 'threads', ['thread_id'], ['id'])
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    # ### end Alembic commands ###
