"""add config_values to runs

Revision ID: 9e7371e978bd
Revises: 726a83d69404
Create Date: 2026-03-18 14:39:21.587575+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e7371e978bd'
down_revision: Union[str, None] = '726a83d69404'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('config_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'config_values')
    # ### end Alembic commands ###
