"""add created_at indexes cascade tz aware

Revision ID: 726a83d69404
Revises: a96292c5d628
Create Date: 2026-01-07 11:44:32.273101+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '726a83d69404'
down_revision: Union[str, None] = 'a96292c5d628'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.drop_constraint(op.f('messages_thread_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'threads', ['thread_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_run_steps_created_at'), 'run_steps', ['created_at'], unique=False)
    op.drop_constraint(op.f('run_steps_run_id_fkey'), 'run_steps', type_='foreignkey')
    op.drop_constraint(op.f('run_steps_thread_id_fkey'), 'run_steps', type_='foreignkey')
    op.create_foreign_key(None, 'run_steps', 'runs', ['run_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'run_steps', 'threads', ['thread_id'], ['id'], ondelete='CASCADE')
    op.alter_column('runs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_runs_created_at'), 'runs', ['created_at'], unique=False)
    op.drop_constraint(op.f('runs_thread_id_fkey'), 'runs', type_='foreignkey')
    op.create_foreign_key(None, 'runs', 'threads', ['thread_id'], ['id'], ondelete='CASCADE')
    op.alter_column('threads', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('threads', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('run_steps', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('run_steps', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_threads_created_at'), 'threads', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threads_created_at'), table_name='threads')
    op.alter_column('threads', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('threads', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'runs', type_='foreignkey')
    op.create_foreign_key(op.f('runs_thread_id_fkey'), 'runs', 'threads', ['thread_id'], ['id'])
    op.drop_index(op.f('ix_runs_created_at'), table_name='runs')
    op.alter_column('runs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('runs', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'run_steps', type_='foreignkey')
    op.drop_constraint(None, 'run_steps', type_='foreignkey')
    op.create_foreign_key(op.f('run_steps_thread_id_fkey'), 'run_steps', 'threads', ['thread_id'], ['id'])
    op.create_foreign_key(op.f('run_steps_run_id_fkey'), 'run_steps', 'runs', ['run_id'], ['id'])
    op.drop_index(op.f('ix_run_steps_created_at'), table_name='run_steps')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_thread_id_fkey'), 'messages', 'threads', ['thread_id'], ['id'])
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.alter_column('messages', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('messages', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('run_steps', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('run_steps', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
