"""add stream column to runs

Revision ID: fb9d6bd2410c
Revises: c4f1d2e3a5b8
Create Date: 2026-04-28 13:06:06.899582+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb9d6bd2410c'
down_revision: Union[str, None] = 'c4f1d2e3a5b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('stream', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'stream')
    # ### end Alembic commands ###
